name: ✨ 기능 요청 (New Feature)
description: 새로운 기능을 개발해야 할 때 사용합니다.
title: "[FEAT] "
labels: ["feat"]
assignees: []
body:
    - type: markdown
      attributes:
          value: |
              ### 기능 개발 요청
              어떤 기능을 추가해야 하는지 구체적으로 작성해 주세요.

    - type: textarea
      id: summary
      attributes:
          label: 기능 요약 (Summary)
          description: 개발하려는 기능의 개요를 한 문장으로 설명해 주세요.
          placeholder: "원격 저장소에서 패키지 목록을 받아오는 기능 구현"
      validations:
          required: true

    - type: textarea
      id: detail
      attributes:
          label: 상세 내용 (Detail)
          description: 기능의 작동 방식, 필요한 데이터, 예외 처리 등을 상세히 기술해 주세요.
      validations:
          required: true

    - type: textarea
      id: references
      attributes:
          label: 참고 자료 (References)
          description: 관련된 디자인 시안, 기술 문서, 또는 관련 이슈 링크를 남겨주세요.
      validations:
          required: false
